apiVersion: v1
kind: Service
metadata:
  name: webtop
  labels:
    app: webtop
  annotations:
    metallb.universe.tf/address-pool: poke-verse
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: web
  selector:
    app: webtop