apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  labels:
    app: jackett
    chart: jackett-0.1.0
    release: jackett
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
      release: jackett
  template:
    metadata:
      labels:
        app: jackett
        release: jackett
    spec:
      volumes:
      - name: jackett
        hostPath:
          path: /k3s/jackett
      containers:
        - name: jackett
          image: "linuxserver/jackett:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - name: http
              containerPort: 9117
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: jackett
              subPath: configs/jackett
            - mountPath: /downloads
              name: jackett
              subPath: downloads/jackett
          resources:
            limits:
              cpu: 0.5
              memory: 256Mi
            requests:
              cpu: 0.1
              memory: 128Mi
          securityContext:
            {}