apiVersion: v1
kind: Service
metadata:
  name: jackett
  labels:
    app: jackett
    release: jackett
  annotations:
    metallb.universe.tf/address-pool: poke-verse
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9117
      protocol: TCP
      name: http
  selector:
    app: jackett
    release: jackett
