apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: plex
  namespace: plex
  labels:
    app: kube-plex
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: plex
subjects:
  - kind: ServiceAccount
    name: plex
    namespace: "plex"
