apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: plex
  namespace: plex
  labels:
    app: kube-plex
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/attach
      - pods/exec
      - pods/portforward
      - pods/proxy
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
