apiVersion: v1
kind: Service
metadata:
  name: plex-tcp
  namespace: plex
  labels:
    app: plex
  annotations:
    metallb.universe.tf/address-pool: local
    metallb.universe.tf/allow-shared-ip: plex
spec:
  selector:
    app: plex
  type: LoadBalancer
  loadBalancerIP: 192.168.1.200
  ports:
    - port: 32400
      targetPort: 32400
      name: pms-web
      protocol: TCP
    - port: 3005
      targetPort: 3005
      name: plex-companion
    - port: 8324
      name: plex-roku
      targetPort: 8324
      protocol: TCP
    - port: 32469
      targetPort: 32469
      name: dlna-tcp
      protocol: TCP
