apiVersion: v1
kind: Service
metadata:
  name: plex-udp
  namespace: plex
  labels:
    app: plex
  annotations:
    metallb.universe.tf/address-pool: local
    metallb.universe.tf/allow-shared-ip: plex
spec:
  selector:
    app: plex
  type: LoadBalancer
  loadBalancerIP: 192.168.1.200
  ports:
    - port: 1900
      targetPort: 1900
      name: dlna-udp
      protocol: UDP
    - port: 5353
      targetPort: 5353
      name: discovery-udp
      protocol: UDP
    - port: 32410
      targetPort: 32410
      name: gdm-32410
      protocol: UDP
    - port: 32412
      targetPort: 32412
      name: gdm-32412
      protocol: UDP
    - port: 32413
      targetPort: 32413
      name: gdm-32413
      protocol: UDP
    - port: 32414
      targetPort: 32414
      name: gdm-32414
      protocol: UDP
