apiVersion: v1
kind: Service
metadata:
  name: transmission
  labels:
    app: transmission
  annotations:
    metallb.universe.tf/address-pool: local
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.201
  ports:
    - port: 55555
      targetPort: 55555
      protocol: TCP
      name: connectivity
  selector:
    app: transmission