---
apiVersion: v1
kind: Service
metadata:
  namespace: node-red
  name: node-red
  labels:
    app.kubernetes.io/name: node-red
    app.kubernetes.io/instance: node-red
    app.kubernetes.io/version: "1.3.5"
  annotations:
    metallb.universe.tf/address-pool: poke-verse
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: node-red
    app.kubernetes.io/instance: node-red
