apiVersion: apps/v1
kind: Deployment
metadata:
  name: readarr
  labels:
    app: readarr
    release: readarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readarr
      release: readarr
  template:
    metadata:
      labels:
        app: readarr
        release: readarr
    spec:
      volumes:
        - name: readarr
          hostPath:
            path: /k3s/readarr
        - name: downloads
          hostPath:
            path: /k3s/plex/data
      containers:
        - name: readarr
          livenessProbe:
            exec:
              command:
                - curl
                - -s
                - "localhost:8080"
                - ">"
                - /dev/null
            initialDelaySeconds: 5
            periodSeconds: 600
            timeoutSeconds: 60
          image: "linuxserver/readarr:nightly"
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - name: http
              containerPort: 8787
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: readarr
              subPath: configs/readarr
            - mountPath: /books
              name: readarr
              subPath: media/books
            - mountPath: /downloads
              name: downloads
          resources:
            limits:
              cpu: 0.5
              memory: 256Mi
            requests:
              cpu: 0.1
              memory: 128Mi
