apiVersion: v1
kind: Service
metadata:
  name: readarr
  labels:
    app: readarr
    release: readarr
  annotations:
    metallb.universe.tf/address-pool: poke-verse
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8787
      protocol: TCP
      name: http
  selector:
    app: readarr
    release: readarr
