git reapiVersion: v1
kind: Service
metadata:
  namespace: transmission
  name: transmission
  labels:
    app: transmission
  annotations:
    metallb.universe.tf/address-pool: poke-verse
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9091
      protocol: TCP
      name: http
  selector:
    app: transmission