apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app: sonarr
    release: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
      release: sonarr
  template:
    metadata:
      labels:
        app: sonarr
        release: sonarr
    spec:
      volumes:
      - name: sonarr
        hostPath:
          path: /k3s/sonarr
      - name: downloads
        hostPath:
          path: /k3s/plex/data
      containers:
        - name: sonarr
          livenessProbe:
            exec:
              command:
                - curl
                - -s
                - "localhost:8989"
                - ">"
                - /dev/null
            initialDelaySeconds: 5
            periodSeconds: 600
            timeoutSeconds: 60
          image: "linuxserver/sonarr:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - name: http
              containerPort: 8989
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: sonarr
              subPath: configs/sonarr
            - mountPath: /tv
              name: sonarr
              subPath: medias/tv
            - mountPath: /downloads
              name: downloads  
          resources:
            limits:
              cpu: 0.5
              memory: 256Mi
            requests:
              cpu: 0.1
              memory: 128Mi
