apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-alertmanager
spec:
  template:
    spec:
      volumes:
        - name: storage-volume
          hostPath:
            path: /k3s/prometheus/alertmanager
          persistentVolumeClaim:
            $patch: delete