apiVersion: v1
kind: Service
metadata:
  name: wol
  labels:
    app: wol
  annotations:
    metallb.universe.tf/address-pool: poke-verse
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8089
      protocol: TCP
      name: web
  selector:
    app: wol